export const SET_USER_INFO = 'SET_USER_INFO';
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const SHOW_REGISTER_MODAL = 'SHOW_REGISTER_MODAL';
export const SHOW_ALL_ACTIVITIES = 'SHOW_ALL_ACTIVITIES';
export const SHOW_USER_ACTIVITIES_JOIN = 'SHOW_USER_ACTIVITIES_JOIN';
export const SHOW_USER_ACTIVITIES_HOST = 'SHOW_USER_ACTIVITIES_HOST';
